"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import json
from datetime import timedelta
from pathlib import Path

from google.oauth2 import service_account

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
ROOT_DIR = BASE_DIR.parent

SECRET_DIR = ROOT_DIR / '.secrets'
SECRET_COMMON_FILE = SECRET_DIR / 'common.json'
SECRET_DEBUG_FILE = SECRET_DIR / 'debug.json'
SECRET_DEPLOY_FILE = SECRET_DIR / 'deploy.json'
COMMON_SECRET = json.loads(SECRET_COMMON_FILE.read_text())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = COMMON_SECRET['secret_key']

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'raw_data',
    'match',
    'summoner',
    'timeline',
    'event',
    'replay',
    'debug_toolbar',
    'storages',
    'champion',
    'rest_framework',
    'youtube',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RIOT_API_KEYS = COMMON_SECRET['riot_api_keys']

# 매치 데이터를 이 시간 이내에 다시 업데이트할 수 없습니다.
SUMMONER_MIN_UPDATE_TIME = timedelta(days=1)

'''
크롤링할 queue_id 입니다.
450: 칼바람 나락 -> 리플레이를 다운로드할 수 없음
420: 솔랭
'''
MATCH_LIST_QUEUE_ID = 420


# 한 번의 요청에 가져올 match의 갯수입니다.
MATCH_LIST_COUNT = 10

INTERNAL_IPS = (
    '127.0.0.1',
    '192.168.0.3',
    '192.168.0.6',
)

JSON_DATA_REMAIN_COUNT = 100

CLEAN_DATA_LOOP_COUNT = 100

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

BACKUP_HOST = COMMON_SECRET['backup_host']

IS_MAIN_CRAWLER = COMMON_SECRET['is_main_crawler']

MAIN_CRAWLER_HOST = COMMON_SECRET['main_crawler_host']
